"""
Django settings for ai_test project.

Generated by 'django-admin startproject' using Django 5.2.6.
...
"""

from pathlib import Path
import os  # Ensure this is at the top

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-rf^i_@h*%*-6bz7n5djy8d2r26z+e!y-s4=h2g83pv=uptw)gk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # 1. NEW: Custom App, DRF, and JWT added
    "writetset_frontend", 
    "rest_framework",
    "rest_framework_simplejwt",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ai_test.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # 2. UPDATED: Global templates folder added
        "DIRS": [os.path.join(BASE_DIR, "templates")],  
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
WSGI_APPLICATION = "ai_test.wsgi.application"


# Database
# 3. UPDATED: PostgreSQL Configuration
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "aiTest",
        "USER": "swapnil",          
        "PASSWORD": "12345",   
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# ... (No changes here unless required)


# Internationalization
# ... (No changes here unless required)


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django ko batayein ki global static folder kahan hai
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# --- Custom Settings Added Below ---

# 4. NEW: Custom User Model
# Django ko batana ki hamara custom user model kaunsa hai
AUTH_USER_MODEL = 'writetset_frontend.CustomUser'

# 5. NEW: Django REST Framework (DRF) Configuration
REST_FRAMEWORK = {
    # JWT ko default authentication class banana
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# 6. NEW: Simple JWT Configuration (Optional: default settings theek hain)
# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
# }